### ISSUE TITLE
align_camera.ipynb Jupyter notebook

### ISSUE THREAD

**Issue by kcjones** [kbelenky/open_sorts#3]
Thanks for this project. I've decided to give it a go. I don't see the camera aligner notebook in the repo (align_camera.ipynb). Is this something you can share? Or share a config w/ keypoints define to help me work it out on my own?

**Comment by kbelenky** [comment]
Sorry about that.

A while back I eliminated the need for the camera aligner notebook, when I added the automatic corner detector:
https://github.com/kbelenky/open_sorts/blob/main/corner_detector.md

I must have forgotten to update the documentation.

You should be able to disregard the section about the camera aligner notebook now.
